import { IRecipieFullCard } from "../../../type";

export const recipiesInitialState: IRecipieFullCard[] = [
  {
    name: "Risotto de vinho tinto",
    duration: 50,
    servings: 4,
    description:
      "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    level: "easy",
    stars: 4,
    ingredients: [
      "1 c. de sopa azeite",
      "50 gr cebola picada",
      "30 gr aipo (talo)",
      "200 gr arroz para risotto",
      "200 ml vinho tinto",
      "1 caldo de legumes sem sal",
      "750 ml água",
      "1 c. de chá sal",
      "25 gr parmesão ralado",
      "2 c. de sopa cebolinho picado",
    ],
    steps: [
      "Aqueça o azeite num tacho, junte a cebola descascada e picada, o talo de aipo cortado em lâminas finas e cozinhe sobre lume moderado até a cebola começar a alourar.",
      "Junte o arroz e frite durante 1 minuto, mexendo sempre. Refresque com o vinho tinto e deixe cozinhar, mexendo, até o arroz absorver o vinho.",
      "Entretanto, dilua o caldo escolhido em água quente, junte o sal e vá acrescentando ao arroz a pouco e pouco e sem parar de mexer. O arroz demora cerca de 25 minutos a cozer e deve ficar cremoso.",
      "Junte o queijo parmesão e o cebolinho, envolva bem e sirva de imediato como acompanhamento de carnes assadas ou peito de pato.",
    ],
  },
  {
    name: "Salongo recheado à Açoreana",
    duration: 60,
    servings: 6,
    description:
      "O salongo recheado à Açoreana transporta-nos para os sabores típicos das férias de Verão. Acompanhe com o puré, a alface e um vinho bem fresco.",
    level: "medium",
    stars: 3,
    ingredients: [
      "1 kg (2 unid.) salongo ",
      "1 e ½ c. de chá sal",
      "3 cebolas médias",
      "2 dentes de alho",
      "3 c. de sopa azeite",
      "150 g filete de peixe-espada-preto",
      "70 g pão de cereais ancestrais",
      "50 ml água",
      "30 g azeitonas pretas em rodelas",
      "2 c. de sopa salsa fresca",
      "1 c. de sopa vinagre",
      "1 ovo M",
      "qb pimenta de moinho",
      "1 c. de sopa massa de pimentão",
      "100 ml vinho branco",
      "1 emb. puré de batata",
      "100 g espinafres",
      "300 g alface iceberg",
    ],
    steps: [
      "Pré-aqueça o forno a 180 °C.",
      "Lave o peixe, enxugue-o com papel de cozinha e dê dois golpes em diagonal de cada lado do lombo. Salpique com uma colher de chá de sal.",
      " Pique finamente uma cebola e um dente de alho, previamente descascados, e leve a alourar numa frigideira com uma colher de sopa de azeite. Introduza o filete e deixe cozinhar de ambos os lados durante cerca de 5 minutos, à medida que vai desfazendo o peixe com uma espátula. Entretanto, desfaça o pão em pedaços e escalde-o com a água a ferver. Junte o pão bem demolhado ao peixe, adicione uma colher de sopa de salsa picada, as azeitonas e misture muito bem. Retire do lume, junte o vinagre e o ovo batido, tempere com ½ colher de chá de sal e pimenta moída na altura e mexa bem.",
      "Introduza cuidadosamente o recheio na barriga do peixe através da abertura junto à cabeça. Coloque o peixe sobre um tabuleiro de forno untado com um pouco do azeite.",
      "Cubra o peixe com as restantes cebolas e dentes de alho descascados e cortados em rodelas finas.",
      "Regue com a massa de pimentão, dissolvida no vinho branco, e o restante azeite. Leve a assar no forno durante cerca de 35 minutos.",
      "Entretanto prepare o puré de batata, seguindo as indicações da embalagem. Bata o puré com os espinafres cozidos num robot de cozinha, até obter uma mistura homogénea.",
      "Na altura de servir, salpique o peixe com a restante salsa picada e acompanhe com o puré e com a alface.",
    ],
  },
  {
    name: "Suspiros de avelã",
    duration: 60,
    servings: 18,
    description:
      "De origem europeia, o suspiro foi ganhando fãs ao longo do tempo. De confecção fácil, e muito versátil quando combinado com outros ingredientes. Esta versão com avelã é incrivelmente saborosa.",
    level: "easy",
    stars: 2,
    ingredients: [
      "4 c. de sopa creme para barrar de cacau e avelãs",
      "3 claras L",
      "150 g açúcar fino",
      "1 c. de sopa amido de milho ",
      "¼ c. de café sal",
      "150 g avelãs picadas",
    ],
    steps: [
      "Pré-aqueça o forno a 150 °C.",
      "Forre dois tabuleiros de forno com papel vegetal.",
      "Coloque o creme de avelãs numa taça e leve ao microondas por 30 segundos até que fique derretido.",
      "Bata as claras com a ajuda da batedeira até ficarem fofas. Vá adicionando aos poucos o açúcar até obter picos.",
      "Envolva o amido de milho e o sal.",
      "Por último, junte o creme de avelãs derretido e as avelãs picadas e envolva levemente.",
      "Distribua o preparado pelos dois tabuleiros fazendo pequenos montes, com uma separação de alguns centímetros.",
      "Leve ao forno por 20 a 25 minutos, desligue e deixe arrefecer dentro do forno com a porta fechada até perfazer a hora. Decore a gosto.",
    ],
  },
  {
    name: "Manjar de pêras bêbedas em vinho do Porto",
    duration: 105,
    servings: 15,
    description:
      "Cozinhe como um chef e prepare este manjar de pêras bêbedas em vinho do Porto, uma sobremesa que certamente não vai passar despercebida. Experimente!",
    level: "medium",
    stars: 2,
    ingredients: [
      "1 L leite gordo",
      "1 lata de leite condensado Pingo Doce",
      "400 ml (1 lata) leite de coco",
      "200 ml (1 emb.) natas",
      "110 g amido de milho",
      "150 g coco ralado",
      "750 g (8 unid.) pêra rocha descascada",
      "500 ml vinho do Porto",
      "200 ml água",
      "100 g açúcar",
      "6 paus de canela",
      "3 estrelas de anis",
      "1 lima (casca)",
    ],
    steps: [
      "Num liquidificador, bata o leite, o leite condensado, o leite de coco, as natas e o amido de milho. Deite a mistura numa panela, acrescente o coco ralado e mexa bem. Leve ao lume e deixe cozinhar por 20 minutos ou até engrossar, mexendo sempre.",
      "Coloque o creme numa forma de anel molhada com água ou óleo e deixe arrefecer por 30 minutos.",
      "Ponha a forma no frigorífico por 1 hora ou até ficar bem firme.",
      "Entretanto, prepare as pêras. Junte todos os ingredientes num tacho e deixe cozinhar em lume médio. Quando as peras estiverem cozidas, retire-as para um prato e reduza o líquido no tacho até obter o ponto de calda.",
      "Decore o manjar com as pêras laminadas ou se preferir disponha-as à volta do prato, colocando por cima a calda.",
    ],
  },
  {
    name: "Sopa fria de cenoura com especiarias",
    duration: 30,
    servings: 4,
    description:
      "A sopa fria de cenoura tem uma cremosidade incrível e um conjunto de aromas que não vai querer perder. Sirva com cubos de pepino e folhas de manjericão.",
    level: "easy",
    stars: 5,
    ingredients: [
      "50 g (½ unid.) cebola",
      "1 e ½ pepino",
      "320 g (4 unid.) tomate de rama maduro",
      "400 g (4 unid.) cenoura",
      "qb manjericão fresco",
      "1 c. de chá alho em pó",
      "qb paprika",
      "qb cominhos",
      "qb malagueta em pó",
      "qb funcho seco",
      "1 c. de sobremesa sal",
      "2 c. de sopa vinagre de vinho tinto",
      "2 c. de sopa azeite",
    ],
    steps: [
      "Coloque num liquidificador a cebola, previamente descascada, um pepino, sem casca e sementes, cortado em pedaços, o tomate também cortado em pedaços, e as cenouras descascadas e cortadas em cubos. Adicione as especiarias, os temperos e triture até obter um creme. Leve ao frio até servir.",
      "Descasque e corte em cubos pequenos o restante pepino.",
      "Sirva a sopa com os cubos de pepino e decore com manjericão.",
    ],
  },
];
